services:
  dashboard:
    image: ghcr.io/smarthomeka/swimspa-dashboard:latest
    pull_policy: always
    container_name: swimspa-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - swimspa-data:/app/data

volumes:
  swimspa-data:
